services:

  db:
    image: postgres:15
    container_name: shark_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - shark_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shark_redis
    ports:
      - "6399:6379"
    networks:
      - shark_network

  backend:
    build: ./backend
    container_name: shark_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8080:8000"      
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - shark_network

  frontend:
    build: ./frontend
    container_name: shark_frontend
    environment:
      VITE_API_PROXY_TARGET: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules      
    ports:
      - "5199:5173"
    networks:
      - shark_network

volumes:
  postgres_data:

networks:
  shark_network:
    driver: bridge